"""Pydantic models for Fabrivium Phase 2C — scenario comparison / what-if output."""

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field

from app.models.simulation import SimulationResult


# Enums

class Verdict(str, Enum):
    """Deterministic, lexicographic-priority verdict — never a weighted score."""

    IMPROVED = "IMPROVED"
    NEUTRAL = "NEUTRAL"
    DEGRADED = "DEGRADED"


class ScenarioComparisonKind(str, Enum):
    """
    Classifies *what kind* of change a scenario represents, independent of its measured
    outcome.
    """

    ENGINEERING_CHANGE = "ENGINEERING_CHANGE"
    REQUIREMENT_CHANGE = "REQUIREMENT_CHANGE"
    MIXED_CHANGE = "MIXED_CHANGE"


# Per-process-pool comparison

class ProcessPoolComparison(BaseModel):
    """
    Before/after comparison for one logical process stage (service pool), matched
    between baseline and candidate by ``reference_machine_id`` (==
    ProcessStep.machine_id / pool root — routes are never changed by a scenario, so this
    id is stable across baseline and candidate).
    """

    reference_machine_id: str = Field(..., description="ProcessStep.machine_id / pool root")
    process_step_name: str

    machine_ids_before: list[str]
    machine_ids_after: list[str]

    utilization_before: float = Field(..., ge=0.0, le=1.0)
    utilization_after: float = Field(..., ge=0.0, le=1.0)
    utilization_delta: float

    average_queue_before: float = Field(..., ge=0.0)
    average_queue_after: float = Field(..., ge=0.0)
    average_queue_delta: float

    max_queue_before: int = Field(..., ge=0)
    max_queue_after: int = Field(..., ge=0)

    average_wait_before: float = Field(..., ge=0.0)
    average_wait_after: float = Field(..., ge=0.0)
    average_wait_delta: float


# Top-level comparison

class ScenarioComparison(BaseModel):
    """Engineering deltas between a baseline and candidate SimulationResult."""

    comparison_kind: ScenarioComparisonKind

    # Demand / target — see ScenarioComparisonKind for why target changes
    # must be treated separately from engineering changes.
    baseline_target_units: int
    candidate_target_units: int
    target_units_changed: bool

    demand_met_before: bool
    demand_met_after: bool

    demand_gap_units_before: float = Field(..., ge=0.0)
    demand_gap_units_after: float = Field(..., ge=0.0)
    demand_gap_delta: float = Field(
        ..., description="candidate.demand_gap_units - baseline.demand_gap_units; negative == improvement"
    )

    # Throughput / completion
    completed_units_before: int = Field(..., ge=0)
    completed_units_after: int = Field(..., ge=0)
    completed_units_delta: int

    throughput_per_hour_delta: float
    throughput_percent_change: float | None = Field(
        None, description="None when baseline throughput_per_hour == 0 and candidate != 0"
    )

    # WIP / flow time
    wip_before: int = Field(..., ge=0)
    wip_after: int = Field(..., ge=0)
    wip_delta: int

    average_flow_time_before_seconds: float = Field(..., ge=0.0)
    average_flow_time_after_seconds: float = Field(..., ge=0.0)
    average_flow_time_delta_seconds: float
    average_flow_time_percent_change: float | None = Field(
        None, description="None when baseline average_flow_time_seconds == 0 and candidate != 0"
    )

    # Bottleneck
    bottleneck_before: str
    bottleneck_after: str
    bottleneck_changed: bool

    # CAPEX — informational only; see app.services.comparison.calculate_capex_delta.
    capex_delta: float | None = Field(
        None, ge=0.0, description="Sum of scenario-action CAPEX, Phase 2C rules; None = not known"
    )

    # Per-logical-stage detail
    process_pool_comparisons: list[ProcessPoolComparison] = Field(default_factory=list)


# Top-level scenario result

class ScenarioResult(BaseModel):
    """Full output of one what-if evaluation: baseline + candidate
    simulations, their comparison, and a deterministic verdict."""

    scenario_id: str
    scenario_name: str

    baseline_result: SimulationResult
    candidate_result: SimulationResult
    comparison: ScenarioComparison

    verdict: Verdict
    verdict_reasons: list[str] = Field(
        ...,
        description=(
            "Deterministic, human-readable explanations for the verdict, in "
            "priority order. Generated by plain formatted strings — never by "
            "an LLM — so they are exactly reproducible for identical inputs."
        ),
    )
