"""Repository-wide Golden-Run coupling scan (Fabrivium generalization, Gate A)."""

from __future__ import annotations

import argparse
import io
import json
import pathlib
import re
import sys
import tokenize
from dataclasses import dataclass, field

ROOT = pathlib.Path(__file__).resolve().parents[2]

# What is scanned

# Directories that never contain hand-written source.
_SKIP_DIRS = {
    ".git", "node_modules", "__pycache__", "dist", "build",
    ".pytest_cache", ".hypothesis", ".venv", "venv", ".mypy_cache",
    ".playwright-mcp", ".ruff_cache",
}

# Extensions worth reading.
_SCAN_EXT = {".py", ".ts", ".tsx", ".js", ".mjs", ".jsx", ".json", ".md", ".txt", ".css", ".html"}

# Files above this size are data dumps (recorded runs, transcripts), not code.
_LARGE_FILE_BYTES = 2_000_000


# What is looked for

@dataclass(frozen=True)
class Token:
    """One coupling probe."""

    name: str
    pattern: re.Pattern[str]
    # What this probe is evidence of, printed in the report.
    meaning: str


def _rx(pattern: str) -> re.Pattern[str]:
    return re.compile(pattern, re.IGNORECASE)


# The brief's search list, as anchored patterns.
TOKENS: tuple[Token, ...] = (
    Token("CEC-120", _rx(r"\bCEC[-\s]?120\b"), "the golden product's identity"),
    Token("golden figures", _rx(r"\b(1[, ]?900|1[, ]?435|1[, ]?058|2[, ]?033|465)\b"),
          "target / baseline / gap / measured throughput of the golden run"),
    Token("golden cost", _rx(r"\b(18[, ]?000|18k)\b"), "the golden run's OPEX figure"),
    Token("golden operations", _rx(r"\b(cable connection|screw fastening|PCB placement|visual inspection)\b"),
          "operation names generated by the golden route"),
    Token("domain vocabulary", _rx(r"\b(screwdriv\w*|PCB|soldering|palletiz\w*)\b"),
          "electronics/bench-assembly process vocabulary"),
    Token("golden schedule", _rx(r"\b(2 shifts|8 operators|7 stations|30 ?[x×] ?18)\b"),
          "the golden run's schedule, workforce and floor"),
    Token("golden run counts", _rx(r"\b(23 simulations|3 strategies)\b"), "the golden run's reported activity"),
    Token("plan labels", _rx(r"\bPlan [ABC]\b"), "display labels for interventions"),
    Token("demo vocabulary", _rx(r"\b(golden[_ -]?run|demo[_ -]?mode|demoStage|example[_ -]?data|test fixture)\b"),
          "demonstration scaffolding"),
)

# Probes whose production occurrences are DOMAIN COVERAGE, not Golden-Run coupling.
_DOMAIN_TOKENS = frozenset({"domain vocabulary"})

# Class F probes: a production BRANCH keyed on the demo or on a product identity.
_CONTROL_FLOW: tuple[re.Pattern[str], ...] = (
    _rx(r"\bif\b[^\n]{0,80}\b(is_demo|demo_mode|golden|cec[-_]?120)\b"),
    _rx(r"\b(product_name|productName|product\.name)\s*[=!]=\s*['\"]"),
    # A COUNT assumption, e.g.
    _rx(r"\b(operations|stages|stations|machines)\s*\.\s*length\s*===?\s*[1-9]"),
    _rx(r"\blen\(\s*(operations|stages|stations|machines)[^)]*\)\s*==\s*[1-9]"),
)


# Zone: where does this file live?

PRODUCTION = "production"
TEST = "test"
EXAMPLE = "example"
DOCUMENTATION = "documentation"


def zone_of(rel: pathlib.PurePosixPath) -> str:
    parts = rel.parts
    name = rel.name

    if parts and parts[0] in {"examples", "demo", "presentation", "projects", "exports", "simulation", "tests"}:
        return EXAMPLE
    if parts[:2] == ("backend", "tests") or parts[:2] == ("backend", "scripts"):
        return TEST if parts[1] == "tests" else EXAMPLE
    if ".test." in name or ".spec." in name:
        return TEST
    if parts[:3] == ("frontend", "src", "test"):
        return TEST
    if rel.suffix == ".md":
        return DOCUMENTATION
    if parts[:2] == ("backend", "app") or parts[:2] == ("frontend", "src"):
        return PRODUCTION
    if parts[:1] == ("docs",):
        return DOCUMENTATION
    return EXAMPLE


# Commentary detection — the fact a grep cannot supply

def python_commentary_lines(source: str) -> set[int]:
    """Every 1-based line of *source* that is a comment or a docstring."""
    lines: set[int] = set()
    try:
        tokens = list(tokenize.generate_tokens(io.StringIO(source).readline))
    except (tokenize.TokenError, IndentationError, SyntaxError):
        return lines

    prev_meaningful: int | None = None
    for tok in tokens:
        if tok.type == tokenize.COMMENT:
            lines.update(range(tok.start[0], tok.end[0] + 1))
        elif tok.type == tokenize.STRING:
            # A docstring is a bare string expression: the previous
            # meaningful token is NEWLINE, INDENT, DEDENT or nothing.
            if prev_meaningful in (None, tokenize.NEWLINE, tokenize.INDENT, tokenize.DEDENT):
                lines.update(range(tok.start[0], tok.end[0] + 1))
        if tok.type not in (tokenize.NL, tokenize.COMMENT):
            prev_meaningful = tok.type
    return lines


_TS_LINE_COMMENT = re.compile(r"^\s*(//|\*|/\*)")


def ts_commentary_lines(source: str) -> set[int]:
    """Approximate comment lines for TypeScript/JavaScript."""
    lines: set[int] = set()
    in_block = False
    for number, line in enumerate(source.splitlines(), start=1):
        if in_block:
            lines.add(number)
            if "*/" in line:
                in_block = False
            continue
        stripped = line.strip()
        if _TS_LINE_COMMENT.match(stripped):
            lines.add(number)
        if "/*" in line and "*/" not in line.split("/*", 1)[1]:
            in_block = True
            lines.add(number)
    return lines


def commentary_lines(path: pathlib.Path, source: str) -> set[int]:
    if path.suffix == ".py":
        return python_commentary_lines(source)
    if path.suffix in {".ts", ".tsx", ".js", ".jsx", ".mjs"}:
        return ts_commentary_lines(source)
    if path.suffix == ".css":
        # CSS has only /* */ comments, and the TS scanner's block handling
        # covers them exactly (there is no // and no string-quoted opener).
        return ts_commentary_lines(source)
    # Markdown, JSON, plain text: every line is data or prose, never a branch.
    return set()


# Classification

CLASS_A = "A TEST FIXTURE"
CLASS_B = "B EXAMPLE DATA"
CLASS_C = "C COMPETITION COPY"
CLASS_D = "D DOMAIN DEFAULT"
CLASS_E = "E PRODUCTION HARD-CODING"
CLASS_F = "F HIDDEN GOLDEN-RUN COUPLING"

#: Production files whose executable Golden-Run literals are a declared
#: DOMAIN DEFAULT rather than hard-coding: a published rule table or an
#: anchor a test pins. Each entry names WHY, and the reason is printed in
#: the report so the exemption is argued rather than asserted.
_DECLARED_DEFAULTS: dict[str, str] = {
    "backend/app/data/engineering_reference_data.py":
        "Reference bands and their declared anchor dataset. The anchor values are "
        "recorded so the bands can be checked against measurement; they are never "
        "returned as an estimate (pinned by test_engineering_reference_data).",
    "backend/app/data/electronics_controller_reference_product.txt":
        "The bundled reference specification served by GET /product/reference. It is "
        "INPUT to the same extractor an uploaded document goes through, not a rule.",
    "backend/app/services/concept_builder.py":
        "_STAGE_VOCABULARY — the canonical twelve process families and their aliases. A "
        "list, not a branch; its SIZE is the coverage limit, and that is Phase 4's question.",
    "backend/app/services/process_planning.py":
        "The fact-to-operation rule table. Keyed by fact key, not by product; a product "
        "stating no PCB gets no PCB rule. Coverage is a domain-pack question.",
    "backend/app/services/product_extraction.py":
        "Fact vocabularies (countables, inspection phrases). Lists of things a "
        "specification may say, matched by phrase; nothing branches on the product.",
    "backend/app/services/local_estimator.py":
        "Estimation keyword tables mapping a described operation to a reference band.",
    "backend/app/services/equipment_discovery.py":
        "process_type -> EquipmentCapability map, used to pick a requirement template.",
    "backend/app/data/screwdriving_candidates.json":
        "A researched equipment dataset for ONE process category. Looked up by category; "
        "any other category returns an empty shortlist plus a note. Coverage, not a branch.",
    "backend/app/data/visual_inspection_candidates.json":
        "As above, for the visual-inspection category.",
    "backend/app/data/label_application_candidates.json":
        "As above, for the label-application category.",
    "backend/app/data/internal_asset_pool.json":
        "The customer's own already-owned assets. Example data in a production path only "
        "because a real deployment replaces the file.",
    "backend/app/knowledge/adapters/estimation.py":
        "Knowledge-base estimation adapter prose.",
    "frontend/src/utils/assetResolution.ts":
        "3D asset lookup by process family, with a generic fallback for an unknown family.",
}

# Production UI files whose Golden-Run literals are placeholder or example-prompt copy.
_UI_EXAMPLE_COPY: dict[str, str] = {
    "frontend/src/components/executive/GoalInput.tsx": "example goal prompts",
    "frontend/src/components/conversation/ConversationPanel.tsx": "example prompts",
    "frontend/src/components/concept/ConceptBuilder.tsx": "example brief and placeholder",
    "frontend/src/components/strategy/StrategyAskBox.tsx": "example refinement sentences",
    "frontend/src/components/product/ProductStart.tsx": "input placeholder",
    "frontend/src/index.css": "comments citing the measured run",
}

# Production files that are UI copy — placeholders and example prompts.
_UI_COPY_HINTS = re.compile(r"(placeholder|example|suggest|hint|PROMPTS?|SAMPLES?)", re.IGNORECASE)


@dataclass
class Hit:
    path: str
    line: int
    token: str
    meaning: str
    text: str
    zone: str
    executable: bool
    classification: str
    action: str


@dataclass
class Report:
    hits: list[Hit] = field(default_factory=list)
    files_scanned: int = 0
    unreadable: list[str] = field(default_factory=list)

    def by_class(self) -> dict[str, int]:
        counts: dict[str, int] = {}
        for hit in self.hits:
            counts[hit.classification] = counts.get(hit.classification, 0) + 1
        return counts


def classify(
    path: str,
    zone: str,
    executable: bool,
    text: str,
    control_flow: bool,
    token_name: str,
) -> tuple[str, str]:
    """Return ``(classification, required action)``."""
    if control_flow:
        return CLASS_F, "CRITICAL — a production branch keyed on the demo or a product identity. Remove."

    if zone == TEST:
        return CLASS_A, "None. A fixture may name the golden case; that is what a regression is."
    if zone == EXAMPLE:
        return CLASS_B, "None, while it stays out of the production import graph."
    if zone == DOCUMENTATION:
        return CLASS_C, "None. Prose about a measured run."

    # Production.
    if not executable:
        return CLASS_C, "None. Commentary citing the measured run as a worked example."
    if path in _DECLARED_DEFAULTS:
        return CLASS_D, f"Review only. {_DECLARED_DEFAULTS[path]}"
    if path in _UI_EXAMPLE_COPY:
        return CLASS_C, (
            f"Presentation only ({_UI_EXAMPLE_COPY[path]}). Should become domain-derived "
            "once a project declares its domain, so a packaging project is not prompted "
            "with an electronics example."
        )
    if token_name in _DOMAIN_TOKENS:
        return CLASS_D, (
            "Review as DOMAIN COVERAGE, not coupling: a process-family vocabulary entry. "
            "The question it raises is which domains are covered, not whether the golden "
            "run leaked."
        )
    if _UI_COPY_HINTS.search(text):
        return CLASS_D, (
            "Review. UI placeholder/example copy: presentation-only, but it teaches a new "
            "user the golden run's shape of input. Should be domain-derived where a domain is known."
        )
    return CLASS_E, "MUST REMOVE — an executable production occurrence of a Golden-Run literal."


# Scan

def iter_files(root: pathlib.Path):
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        if any(part in _SKIP_DIRS for part in path.parts):
            continue
        if path.suffix.lower() not in _SCAN_EXT:
            continue
        yield path


def scan(root: pathlib.Path = ROOT) -> Report:
    report = Report()
    for path in iter_files(root):
        rel = pathlib.PurePosixPath(path.relative_to(root).as_posix())
        try:
            source = path.read_text(encoding="utf-8", errors="replace")
        except OSError as exc:  # a file being written by another process
            report.unreadable.append(f"{rel}: {exc}")
            continue

        report.files_scanned += 1
        zone = zone_of(rel)
        big = len(source) > _LARGE_FILE_BYTES

        # Cheap pre-filter: most files contain none of the probes.
        if not any(token.pattern.search(source) for token in TOKENS) and not any(
            rx.search(source) for rx in _CONTROL_FLOW
        ):
            continue

        comments = set() if big else commentary_lines(path, source)

        for number, line in enumerate(source.splitlines(), start=1):
            control_flow = zone == PRODUCTION and any(rx.search(line) for rx in _CONTROL_FLOW)
            matched = [token for token in TOKENS if token.pattern.search(line)]
            if not matched and not control_flow:
                continue

            executable = number not in comments
            token = matched[0] if matched else Token("control flow", _rx("x"), "a branch")
            classification, action = classify(
                str(rel), zone, executable, line, control_flow, token.name
            )
            report.hits.append(
                Hit(
                    path=str(rel),
                    line=number,
                    token=token.name,
                    meaning=token.meaning,
                    text=line.strip()[:200],
                    zone=zone,
                    executable=executable,
                    classification=classification,
                    action=action,
                )
            )
    return report


# Output

def render_markdown(report: Report) -> str:
    out: list[str] = []
    counts = report.by_class()
    out.append("| Class | Occurrences |")
    out.append("|---|---:|")
    for name in (CLASS_A, CLASS_B, CLASS_C, CLASS_D, CLASS_E, CLASS_F):
        out.append(f"| {name} | {counts.get(name, 0)} |")
    out.append("")

    for name in (CLASS_F, CLASS_E, CLASS_D):
        rows = [hit for hit in report.hits if hit.classification == name]
        out.append(f"### {name} — {len(rows)}")
        out.append("")
        if not rows:
            out.append("None.")
            out.append("")
            continue
        out.append("| File | Line | Coupling | Required action |")
        out.append("|---|---:|---|---|")
        for hit in rows:
            text = hit.text.replace("|", "\\|")
            out.append(f"| `{hit.path}` | {hit.line} | {hit.token} — `{text}` | {hit.action} |")
        out.append("")
    return "\n".join(out)


def main(argv: list[str] | None = None) -> int:
    # The report quotes source lines, which contain arrow and dash
    # characters the Windows console's default cp1252 cannot encode. Force
    # UTF-8 rather than letting the scan die on a quotation mark.
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--json", action="store_true", help="machine-readable output")
    parser.add_argument("--markdown", action="store_true", help="audit table")
    args = parser.parse_args(argv)

    report = scan()

    if args.json:
        print(json.dumps({
            "files_scanned": report.files_scanned,
            "counts": report.by_class(),
            "unreadable": report.unreadable,
            "hits": [hit.__dict__ for hit in report.hits],
        }, indent=2))
    elif args.markdown:
        print(render_markdown(report))
    else:
        print(f"scanned {report.files_scanned} files")
        for name, count in sorted(report.by_class().items()):
            print(f"  {name:<32} {count}")
        for hit in report.hits:
            if hit.classification in (CLASS_E, CLASS_F):
                print(f"  !! {hit.path}:{hit.line}  {hit.text}")
        if report.unreadable:
            print(f"  unreadable: {len(report.unreadable)}")

    blocking = sum(1 for hit in report.hits if hit.classification in (CLASS_E, CLASS_F))
    return 1 if blocking else 0


if __name__ == "__main__":
    sys.exit(main())
